MPICC = mpicc
CFLAGS = -std=c99

problem1: problem1.c
	$(MPICC) $(CFLAGS) problem1.c -o problem1

problem1_d: problem1_d.c
	$(MPICC) $(CFLAGS) problem1_d.c -o problem1_d

clean:
	rm -rf problem1 problem1_d
	@echo cleaning copmplete

